### ISSUE TITLE
disc number / total discs support

### ISSUE THREAD

**Issue by Bilalh** [jamesrhurst/rust-id3#2]
Can support for disc number / total discs, be added?

The field for  the disc number / total discs is  `TPOS` (ID3v2.3, ID3v2.4) or `TPA` (ID3v2.2) and has exactly the same format as the track number.

The functions would be  the as the same as the track functions i.e `set_total_tracks`  & `total_tracks` but using the field for the disk number instead.

**Comment by jamesrhurst** [comment]
I've added functions to manage the disc number and total discs. Let me know if you encounter any problems with the new functions.

**Comment by Bilalh** [comment]
Works for me
